version: '3.8'

services:
  auth2-go:
    build:
      context: .
    container_name: auth2-go
    hostname: rest-server
    env_file:
      - .env
    ports:
      - 80:8080
    deploy:
      restart_policy:
        condition: on-failure
